name: Build NetHunter Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      with:
        ref: kernel-tree-wip

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf lib32ncurses5-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev libelf-dev clang LLVM

    - name: Download AOSP Clang
      run: |
        git clone --depth=1 https://github.com/Panchajanya1999/azure-clang.git clang

    - name: Compile Kernel
      run: |
        # Задаем базовую архитектуру
        export ARCH=arm64
        export SUBARCH=arm64
        
        # Переменные путей к нашему скачанному Android-тулчейну
        CLANG_DIR=$GITHUB_WORKSPACE/clang
        
        # Полная принудительная очистка
        make O=out clean
        make O=out mrproper

        # 1. Генерируем .config. 
        # Используем родной хостовый GCC/Clang для конфигуратора, чтобы не было ошибок triple x86_64
        make O=out lancelot_defconfig HOSTCC=gcc HOSTCXX=g++

        # 2. Запускаем компиляцию ядра.
        # Передаем абсолютные пути к бинарникам Android Clang.
        # В таком режиме HOSTCC (для fixdep) останется системным gcc, а ядро соберется целевым компилятором.
        make O=out \
          HOSTCC=gcc \
          HOSTCXX=g++ \
          CC=${CLANG_DIR}/bin/clang \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CROSS_COMPILE=${CLANG_DIR}/bin/aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=${CLANG_DIR}/bin/arm-linux-gnueabi- \
          LD=${CLANG_DIR}/bin/ld.lld \
          AR=${CLANG_DIR}/bin/llvm-ar \
          NM=${CLANG_DIR}/bin/llvm-nm \
          OBJCOPY=${CLANG_DIR}/bin/llvm-objcopy \
          OBJDUMP=${CLANG_DIR}/bin/llvm-objdump \
          STRIP=${CLANG_DIR}/bin/llvm-strip \
          -j$(nproc)

    - name: Upload Kernel Output
      uses: actions/upload-artifact@v4
      with:
        name: NetHunter-Kernel-Image
        path: out/arch/arm64/boot/Image.gz-dtb
        
